--createdb home-depot-clone

DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS site_user;

CREATE TABLE category (
    category_id SERIAL PRIMARY KEY,
    category_name TEXT NOT null
);

CREATE TABLE item (
    item_id SERIAL,
    item_name TEXT ,
    item_image TEXT,
    item_brand TEXT ,
    item_category INT REFERENCES category(category_id) ON DELETE CASCADE,
    item_price INT ,
    item_type TEXT ,
    item_description TEXT 
);

CREATE TABLE  site_user (
    user_id SERIAL,
    username TEXT NOT null,
    password Text NOT null
);

------test data------

------ test category -----
--INSERT INTO category (category_name) VALUES ('Test category');

----- test item ------
-- INSERT INTO item (item_name, item_brand, item_category, item_price, item_type, item_description) VALUES ('Test Items', 'Test Breand', 1, 1999, 'Test Hammer', 'put all  the nails you want with this tool');

------ test user ------ 
--INSERT INTO site_user (username, password) VALUES ('TEST', '123')

-----categorys------
INSERT INTO category (category_name) VALUES ('Appliances');
INSERT INTO category (category_name) VALUES ('Bath & Faucets');
INSERT INTO category (category_name) VALUES ('Blinds & Window Treatment');
INSERT INTO category (category_name) VALUES ('Building Matrials');
INSERT INTO category (category_name) VALUES ('cleaning');
INSERT INTO category (category_name) VALUES ('Decor & Furniture');
INSERT INTO category (category_name) VALUES ('Doors & Windows');
INSERT INTO category (category_name) VALUES ('Eletrical');
INSERT INTO category (category_name) VALUES ('Flooring & Rugs');
INSERT INTO category (category_name) VALUES ('Hardware');
INSERT INTO category (category_name) VALUES ('Heating & Cooling');
INSERT INTO category (category_name) VALUES ('Holiday Decorations');
INSERT INTO category (category_name) VALUES ('Kitchen');
INSERT INTO category (category_name) VALUES ('Lawn & Garden');
INSERT INTO category (category_name) VALUES ('Lighting & Ceiling Fans');
INSERT INTO category (category_name) VALUES ('Outdoor Living');
INSERT INTO category (category_name) VALUES ('Paint');
INSERT INTO category (category_name) VALUES ('Plumbing');
INSERT INTO category (category_name) VALUES ('Smart Home');
INSERT INTO category (category_name) VALUES ('Storage & Organization');
INSERT INTO category (category_name) VALUES ('Tools');

-----items-----
INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Profile 27.9 cu. ft. Smart 4-Door French Door Refrigerator with Door in Door in Fingerprint Resistant Stainless Steel', 'https://images.thdstatic.com/productImages/e0992f31-7411-415c-8860-be62d86f2d49/svn/fingerprint-resistant-stainless-steel-ge-profile-french-door-refrigerators-pvd28bynfs-64_300.jpg', 'GE', 1, 4199.00, 'Refrigerator', 'Built on the belief that modern life needs modern solutions. GE Profile Appliances are designed to make daily life simpler by incorporating Smart Home technology and cutting-edge features in every appliance. GE Profile''s sleek design and quality engineering will give your kitchen the most up-to-date look and the best innovative performance you''ve been looking for.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Cursiva Single Hole Single-Handle Bathroom Faucet in Vibrant Brushed Nickel', 'https://images.thdstatic.com/productImages/1278988d-9b35-4152-9173-9bd53d69896c/svn/vibrant-brushed-nickel-kohler-single-hole-bathroom-faucets-k-r30577-4d-bn-64_100.jpg', 'KOHLER', 2, 149.00, 'Single-Handle Bathroom Faucet', 'The K-R30577-4D single-handle bathroom sink with lever handle has a warm, contemporary design. Cursiva pairs crisp lines with softened geometric surfaces. It comes with a lifetime limited warranty.
');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Cut-to-Width Walnut Cordless Room Darkening 2.5 in. Distressed Premium Faux Wood Blind - 70 in. W x 72 in. L', 'https://images.thdstatic.com/productImages/76fa9081-13df-4f21-9982-e478c018629b/svn/walnut-faux-wood-blinds-dfhsc7272-70-64_100.jpg', 'Generic', 3, 169.00, 'Faux Wood Blinds', 'These Faux Wood Blidns have a emulate wood grain that is printed directly onto the slast and its offer an sophisticated look and are suitable for any room in the house. Our blinds provide you an excellent choice for light control, as well as for privacy. No lift cords for a clean, uncluttered look. This elimination of lift cords make it the safest option for a home with small children or pets. Available in a variety of sizes.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('2 in x 4 in', 'https://images.thdstatic.com/productImages/4f6b481e-d93a-42d2-835d-739c7b26a3f5/svn/brown-prowood-decking-106147-64_100.jpg', 'Home Depot', 4, 4.58, 'Lumber', '#2 Ground Contact Pressure-Treated Lumber');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('The Original Scrub Daddy', 'https://images.thdstatic.com/productImages/e735177b-84d6-40b3-9f2b-20b145eb5a8e/svn/scrub-daddy-sponges-scouring-pads-sd2013i-64_100.jpg', 'Scrub Daddy', 5, 3.98, 'cleaning tool', 'Scrub Daddy is an innovative household scrubbing tool. His exclusive FlexTexture foam changes texture based on water temperature: firm in cold water for tough scrubbing and soft in warm water for light cleaning. He works so well with water alone many times you can skip using a chemical detergent. Unlike traditional sponges, Scrub Daddy resists stains, mold and odors while never scratching your surfaces. and if you thought the smiley face was just for looks, think again. His eyes hold onto your fingers for a 360° reach (great for tall glasses) and his mouth cleans both sides of your utensils at the same time. Plus, Scrub Daddy rinses clean after use and is top rack dishwasher safe. Use him in the kitchen and beyond.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('33 Gal. Drawstring Blue Recycling Bags (45-Count)', 'https://images.thdstatic.com/productImages/c05ffe9d-86c6-4883-8f71-a05d4e66ac07/svn/ultrasac-garbage-bags-ul-33-gal-blue-recycling-ds-64_300.jpg', 'Ultrasac', 5, 12.94, 'Garbage Bags', 'Ultrasac 33 Gal. Drawstring Blue Recycling Bags are great for all your recycling needs. The blue tint makes these bags ideal for sorting and storing recyclables. Easy drawstring closure. Manufactured from a high-strength prime resin for durability and tear and puncture resistance. A star-sealed bottom seal ensures leak-proof security for the heaviest of loads.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Paradise Palm Cerise Pink Vinyl Strippable Roll', 'https://images.thdstatic.com/productImages/d1f34e5a-0a85-4ff3-a8b3-56ce8d1cad1e/svn/nextwall-wallpaper-rolls-nw33001-64_100.jpg', 'NextWall', 6, 34.99, 'Wall paper', 'With a trendy color palette this Paradise Palm peel and stick wallpaper from NextWall adds a coastal chic look to any wall or furniture surface. Embrace your love of calming ocean breezes and beach living with this contemporary pattern. Printed on smooth vinyl, our self-adhesive designs are perfect for renters and homeowners looking for an instant, DIY transformation to their interior space. With the same qualities and durability as permanent wallpaper, our products offer an easy, fresh alternative to decorating with very little commitment. No water, no mess, no sticky residue.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Regency Modern Customizable Fiberglass Door Collection', 'https://blinds.homedepot.com/is/image/blinds/1+Regency-Fiberglass-5-Lite-Stacked-Mahogany-Finsih-Onyx-Stain-Frosted-Glass-2-Sidelites-%26-Transom-shutterstock_1k1k+(1).jpg?fmt=jpeg&fit=constrain,1&hei=145', 'Steves & Sons', 7, 770.00, 'Exterior Door', 'Add sophistication and durability to your entryway with the Steves and Sons Regency Modern Customizable Collection''s pre-finished fiberglass doors. It features prefinished colors in Ashwood, Chestnut, Hickory, Onyx or Autumn Wheat. Engineered with a 3-inch solid LVL door edge and polyurethane core, this fiberglass unit simulates the resonance of real wood. It has a rot free system that is designed with a composite frame, protecting it against the effects of the elements.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Skylark Contour LED+ Dimmer Switch', 'https://images.thdstatic.com/productImages/4234409e-9c07-44eb-863e-7b7780326ab6/svn/white-lutron-dimmers-ctcl-153pdh-wh-64_100.jpg', 'Lutron', 8, 2497.00, 'Eletrical swittch', 'The Contour LED+ dimmer switch provides optimal dimming performance of LED bulbs. This dimmer switch works with up to 150-Watt of dimmable LED/CFL or 600-Watt of incandescent/halogen, allowing you to control multiple bulb types on the same circuit. It is designed to control a broad range of dimmable LED and CFL bulbs from a variety of brands including Philips, Cree, GE, EcoSmart and Lighting Science. The Contour dimmer switch features a smooth slide, captive knob to adjust your light to any activity. Use the rocker switch to turn your lights off or on returning the lights to your favorite level. Coordinating Claro wall plate sold separately.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('5 in. x 7 in. American Vintage Tawny Oak Engineered Scraped Hardwood Flooring', 'https://images.thdstatic.com/productImages/05c18b3c-c7bd-42c5-afe1-40d51123fd1c/svn/tawny-bruce-br-738547-64_100.jpg', 'Bruce', 9, 2.99, 'Hardwood Flooring', 'Presenting Bruce American Vintage Scrape, an authentic textured hardwood collection that captures the essence of beautiful American craftsmanship. Individually scraped 5 in. wide planks in random lengths provide ageless charm to any decor, creating the custom look of a vintage hand-scraped floor for less. Love your floor for years to come with the protection of our Lifetime Finish and the assurance of a Limited Lifetime Warranty. American Vintage Scrape hardwood floors are made with more than 90% domestic content.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('#9 x 2-1/2 in. Star Drive Bugle Head R4 Multi-Purpose Screw (100-per Pack)', 'https://images.thdstatic.com/productImages/0be8c858-717a-449a-9cfd-dd172c39f861/svn/grk-fasteners-wood-screws-103101-e1_100.jpg', 'GRK Fasteners', 10, 14.88, 'Wood Screws', 'They will find a way to end up in your tires and give you a flat at the most inconvenient time posible!');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Wi-Fi Smart Color 7-Day Programmable Smart Thermostat with Color-Changing Touchscreen Display', 'https://images.thdstatic.com/productImages/a3089d26-e4a0-45b3-85bd-201f6728af9d/svn/metallic-honeywell-home-programmable-thermostats-rth9585wf-64_100.jpg', 'Honeywell Home', 11, 179.98, 'Programmable Thermostat', 'Control the temperature in your home with this Honeywell Home Wi-Fi Smart Color 7-Day Programmable Smart Thermostat with Color-Changing Touchscreen Display. The large color touchscreen display makes it easy to choose a temperature and set a schedule. This energy-efficient thermostat is Energy Star certified and reminds you to change your filter.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('9 ft. Dunhill Fir Artificial Christmas Tree with Dual Color LED Lights', 'https://images.thdstatic.com/productImages/5fa007d9-f82d-4f8f-be74-463e11facbdc/svn/national-tree-company-pre-lit-christmas-trees-duh-300d-90-64_100.jpg', 'National Tree Company', 12, 809.99, 'Artificial Christmas Trees', 'This Dunhill Fir tree is pre-strung with 900 Dual Color lights that change from warm white to multicolor with the touch of a button. The bulbs are low-voltage LEDs that are energy-efficient, long lasting and cool to the touch. Included is a foot pedal switch to control 10 different light colors and actions. Hinged branch construction makes assembly quick and easy.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Hampton 60 in. W x 24 in. D x 34.5 in. H Assembled Sink Base Kitchen Cabinet in Unfinished', 'https://images.thdstatic.com/productImages/213124eb-46cc-429c-a483-c658434ed9a3/svn/unfinished-hampton-bay-assembled-kitchen-cabinets-ksbf60-uf-64_100.jpg', 'Hampton Bay', 13, 204, 'Assembled Kitchen Cabinet', 'The 60 in. Sink Base Cabinet has 2 wood drawer boxes that offer a wide variety of storage possibilities. The cabinet''s doors feature an attractive recessed-panel design, and its solid wood doorframe has a flat insert panel. The unfinished cabinet surface is ready for a coat of paint or stain. The cabinet is pre-configured and fully assembled, saving you time and effort in creating a beautiful home design.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Ultima ZT1 50 in. Fabricated Deck 23HP V-Twin Kawasaki FR Series Engine Dual Hydro Drive Gas Zero Turn Riding Lawn Mower', 'https://images.thdstatic.com/productImages/b563d7dd-4404-4e71-90e7-fecd1440d0ec/svn/cub-cadet-gas-zero-turn-mowers-ultima-zt1-50-64_300.jpg', 'Cub Cadet', 14, 3799.00, 'Outdoor Power Equipment', 'Introducing the ULTIMA ZT1 SERIES. Step up to the ultimate all-around mowing experience. The Cub Cadet ULTIMA Series ZT1 50 features a 23 HP Kawasaki FR691V series Twin-cylinder OHV Engine, 2 in. x 2 in. tubular steel frame, comfortable high back seat and much more. The Ultima Zero-Turn Riding Mower was built to raise the bar for enhanced strength, durability, redefined comfort and uncompromised performance.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('2 Gal. Red Double Knock Out Rose Bush with Red Flowers', 'https://images.thdstatic.com/productImages/c3e374e6-1f64-4500-bf4b-c5574406e0ed/svn/knock-out-rose-bushes-13210-64_300.jpg', 'KNOCK OUT', 14, 27.97, 'Garden Flowers', 'Bring new color to your garden with this Knockout Rose Bush with Red Flowers. These roses are easy to grow and will bloom from spring until frost. These versatile roses are the most disease-resistant on the market so you can keep enjoying them year after year.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Windara 22 in. LED Indoor/Covered Outdoor Brushed Nickel Ceiling Fan with Light Kit and Remote Control', 'https://images.thdstatic.com/productImages/08d2a109-97b1-4c6b-b40d-854a06321128/svn/brushed-nickel-home-decorators-collection-ceiling-fans-with-lights-sfl-550l1-64_300.jpg', 'Home Decorators Collection', 15, 149.99, 'Ceiling Fans With Lights', 'The 22 in. LED Indoor/Covered Outdoor Ceiling Fan with Remote Control offers a better way to cool with Ceiling Fan and LED Light Combination in modern brushed nickel. It features lifetime dimmable LED light strips so you never have to go to the trouble of changing a bulb. 3 speeds make it easy to maintain the perfect amount of airflow with remote control operation. This trendy, space saving fan not only can it be used indoor, but in a covered outdoor space as well. Due to no exposed blades, it''s the perfect addition to a kid''s room, a small kitchen, a dining room or a home office. The 22 in. Enclosed Ceiling Fan and LED Light Combination features a modern, brushed Nickel finish, offers a lifetime warranty on the motor and includes a remote control and an operator''s manual.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Oakshire 4-Piece Wicker Outdoor Deep Seating Set with Tan Cushions', 'https://images.thdstatic.com/productImages/c8b99ff4-25d3-40b4-a326-934fe4bfb5cd/svn/stylewell-patio-conversation-sets-629-64_300.jpg', 'StyleWell', 16, 1076.00, 'Outdoor Lounge Furniture', 'Transform the look and functionality of your outdoor space with the StyleWell Oakshire Four-Piece Outdoor Deep Seating Set. This versatile set is crafted with steel frames with a painted teak finish that will last you over time. The coffee table, two armchairs and loveseat are perfect for outdoor entertaining, plus comfortable tan cushions are included.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('4-Burner Propane Gas Grill in Stainless Steel with Side Burner', 'https://images.thdstatic.com/productImages/7060e02f-7f30-425c-99b7-90ec2075cb52/svn/nexgrill-propane-grills-720-0830x-64_300.jpg', 'Nexgrill', 16, 299.00, 'Propane Grill', 'Meet the Nexgrill 4-Burner Propane Gas Grill in Stainless Steel with 626 sq. in. of total cooking space. With 4 main burners and 1 side burner, supplying 60,000 BTUs of flame-roasting energy, this unit is sure to meet your grilling expectations. The even heat cooking system with stainless steel burners, angled flame tamers and stainless steel cooking grates work together to distribute consistent heat across the entire grilling surface while reducing flare-ups. An electric ignition allows it to fire up instantly and an upper-level warming rack provides a place to heat buns and keep foods toasty. Casters make it easily mobile and the built-in thermometer enables precise temperature regulation. Make your next grill a Nexgrill.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Magnum X7 Stand Airless Paint Sprayer', 'https://www.homedepot.com/p/Graco-Magnum-X7-Stand-Airless-Paint-Sprayer-262805/100634350', 'Graco', 17, 355.91, 'Paint Sprayers', 'Take your painting project to the next level with this Graco Magnum X7 Stand Airless Paint Sprayer. This sprayer is designed for medium-duty projects so it''s great for DIY and pro projects. The sprayer handles up to 15 gallons and you can adjust the pressure to match your project. The stainless steel piston delivers 3000 psi for better atomization that won''t thin your paint or stain. The cart makes it easy to move the sprayer around your home and the hose is 100 ft. long for increased mobility. The SG2 Metal Spray Gun has a filter integrated into the handle to catch debris and prevent tip clogging and the flexible Suction Tube easily adapts to a 1 or 5 gallon bucket of paint or stain When it''s time to clean the sprayer, the PowerFlush adapter connects to your garden hose.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Performance 40 Gal. Medium 6-Year 4500W Electric Tank Water Heater','https://images.thdstatic.com/productImages/79b244db-dc06-4055-9873-feb4e99fb5b9/svn/rheem-electric-tank-water-heaters-xe40m06cg45u0-64_100.jpg', 'Rheem', 18, 579.00, 'Electric Tank Water Heaters', 'Rheem performance 40 gal. electric medium water heater provides an ample supply of hot water for households with 2 to 4 people. This unit comes with (2) 4500-Watt elements and an automatic thermostat which keeps the water at the desired temperature. A 240-Volt electrical connection is required for installation. A premium grade anode rod provides long lasting tank protection. Factory installed temperature and pressure relief valve and 3/4 in. water connections are included with the water heater for easy installation. As a performance tank, it has a 6-year limited tank and parts warranty plus a 1-year in home labor warranty. This model is direct response ready: features a built-in CTA-2045 port for easy connection to utility demand response programs.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Camelot Satin Nickel Electronic Encode Smart WiFi Deadbolt with Alarm', 'https://images.thdstatic.com/productImages/3af3b8bb-5069-4f6e-b7fe-7072e15bf562/svn/schlage-electronic-deadbolts-be489wb-v-cam-619-64_100.jpg', 'Schlage', 19, 289.00, 'Electronic Deadbolts', 'Schlage Encode Smart Wi-Fi Deadbolt offers peace of mind from anywhere by allowing you to remotely manage your lock via the Schlage Home App. There''s no need to purchase an extra accessory/hub to connect to your lock from anywhere it will connect to your homes Wi-Fi signal similar to your laptop, making it easy and intuitive to use. Graded best in security, durability and finish by industry experts, Schlage Encode Smart Wi-Fi Deadbolt offers the advanced features of secure encryption and built-in alarm technology. This innovative smart deadbolt is available in a variety of styles and finishes that pair perfectly with Schlage interior door hardware, creating a cohesive look throughout the home. Backed by a limited lifetime mechanical/finish warranty and 3-year electronics warranty, as well as the strength and durability you can expect from a brand with more than 95-years of experience.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('Ready-to-Assemble 24-Gauge Steel Freestanding Garage Cabinet in Black (36 in. W x 72 in. H x 18 in. D)', 'https://images.thdstatic.com/productImages/0d6e0068-84cf-45be-9c37-68ba0972950a/svn/black-husky-free-standing-cabinets-g3602t-us-e1_100.jpg', 'Husky', 20, 299.25, 'Free Standing Cabinets', 'Easily organize your space with this Ready-to-Assemble 24-Gauge Steel Freestanding Garage Cabinet in Black (36 in. W x 72 in. H x 18 in. D). You can adjust the height to fit your needs. This is an easy DIY project to install. It arrives with all the necessary hardware.');

INSERT INTO item (item_name, item_image, item_brand, item_category, item_price, item_type, item_description) VALUES ('M18 18-Volt Lithium-Ion High Output Starter Kit with Two 6.0 Ah Battery and Charger', 'https://images.thdstatic.com/productImages/3b9bfd39-5c97-41e6-ba34-40932b14a2b6/svn/milwaukee-power-tool-batteries-48-59-1862s-64_300.jpg', 'Milwaukee', 21, 349.00, 'Power Tool Accessories', 'The MILWAUKEE M18 REDLITHIUM HIGH OUTPUT XC6.0 Battery 2-Pack System Starter Kit includes two batteries and an M18/M12 Battery Charger. The M18 REDLITHIUM HIGH OUTPUT XC6.0 Battery Packs provide 50% more power and run 50% cooler than the M18 REDLITHIUM XC battery packs. The optimized combination of size and increased power provides a great solution for the entire range of MILWAUKEE M18 products. It delivers fade-free power and runs substantially cooler through heavy applications, allowing users to push their cordless tools harder and longer than ever before. The M18 REDLITHIUM HIGH OUTPUT XC6.0 provides increased power in extreme cold weather conditions (below 0F / -18C) and delivers more work per charge, driving corded replacement on the jobsite. The REDLITHIUM HIGH OUTPUT XC6.0 battery is fully compatible with over 200 M18 solutions.');
